/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Basic health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/statements/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Non-blocking Statement Ingestion
         * @description Accepts statement payloads, enforces rate/size guardrails, and enqueues to Celery.
         *     Returns HTTP 202 Accepted with a job_id.
         */
        post: operations["ingest_statement_api_v1_statements_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/statements/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Assessment Job Status
         * @description Polls Celery/Redis for job execution status and results.
         */
        get: operations["get_job_status_api_v1_statements_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BankStatementPayload */
        BankStatementPayload: {
            /** Statement Id */
            statement_id: string;
            /** Account Holder */
            account_holder: string;
            /** Account Number */
            account_number: string;
            /** Sort Code */
            sort_code: string;
            /** Transactions */
            transactions: components["schemas"]["Transaction"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestionResponse */
        IngestionResponse: {
            /** Message */
            message: string;
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
        };
        /** Transaction */
        Transaction: {
            /**
             * Id
             * @description Unique transaction ID
             */
            id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Raw Description */
            raw_description: string;
            /** Cleaned Description */
            cleaned_description?: string | null;
            /**
             * Amount
             * @description Positive for income, negative for expenses
             */
            amount: number | string;
            /** @default UNCATEGORISED */
            category: components["schemas"]["TransactionCategory"];
        };
        /**
         * TransactionCategory
         * @enum {string}
         */
        TransactionCategory: "INCOME" | "HOUSING_AND_RENT" | "UTILITIES_AND_BILLS" | "GROCERIES" | "LOAN_REPAYMENT" | "GAMBLING" | "ENTERTAINMENT" | "UNCATEGORISED";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ingest_statement_api_v1_statements_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BankStatementPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_status_api_v1_statements_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
